import ad1 from './ad1.jpg';
import ad2 from './ad2.jpg';
import ad3 from './ad3.jpg';
import ad4 from './ad4.jpg';

let app_pet = [
  {
    id: 1,
    name: "dog",
    category: "dog",
    image: ad1,
    age: "2",
    address: "abc",
    state: "Tamil Nadu",
    PhoneNumber: "000000000000",
    Email: "sample@gmail.com",
    District: "Erode",
  },
  {
    id: 2,
    name: "dog",
    category: "dog",
    image: ad1,
    age: "2",
    address: "abc",
    state: "Kerala",
    PhoneNumber: "000000000000",
    Email: "sample@gmail.com",
    District: "Palakkad",
  },
  {
    id: 3,
    name: "cat",
    category: "cat",
    image: ad3,
    age: "2",
    address: "abc",
    state: "Tamil Nadu",
    PhoneNumber: "000000000000",
    Email: "sample@gmail.com",
    District: "Erode",
  },
  {
    id: 4,
    name: "cat",
    category: "cat",
    image: ad4,
    age: "2",
    address: "abc",
    state: "Tamil Nadu",
    PhoneNumber: "000000000000",
    Email: "sample@gmail.com",
    District: "Erode",
  },
  {
    id: 5,
    name: "cat",
    category: "cat",
    image: ad2,
    age: "2",
    address: "abc",
    state: "Tamil Nadu",
    PhoneNumber: "000000000000",
    Email: "sample@gmail.com",
    District: "Erode",
  },
  {
    id: 6,
    name: "cat",
    category: "cat",
    image: ad2,
    age: "2",
    address: "abc",
    state: "Tamil Nadu",
    PhoneNumber: "000000000000",
    Email: "sample@gmail.com",
    District: "Erode",
  },
];

export default app_pet;
